import { motion, AnimatePresence } from "framer-motion";

interface DesignOption {
  id: string;
  image_url: string;
  style_category: string;
  confidence_score: number;
  metadata?: { style_description?: string };
}

interface DesignArenaProps {
  options: DesignOption[];
  onSelect: (option: DesignOption) => void;
  loading: boolean;
}

export function DesignArena({ options, onSelect, loading }: DesignArenaProps) {
  return (
    <div className="relative grid grid-cols-1 md:grid-cols-2 gap-6 w-full max-w-6xl mx-auto">
      <AnimatePresence>
        {options.map((option, index) => (
          <motion.div
            key={option.id}
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: -20 }}
            transition={{ delay: index * 0.1 }}
            className="group relative aspect-[4/3] bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden cursor-pointer"
            onClick={() => !loading && onSelect(option)}
          >
            {/* Background Image / Placeholder */}
            <div 
              className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110"
              style={{ backgroundImage: `url(${option.image_url})` }}
            />
            
            {/* Dark Overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-zinc-950/20 to-transparent opacity-80" />

            {/* Content */}
            <div className="absolute inset-x-0 bottom-0 p-8 space-y-3">
              <div className="flex justify-between items-end">
                <div className="space-y-1">
                  <span className="text-[0.65rem] font-mono text-amber-500 uppercase tracking-widest block font-black">
                    Archetype 0{index + 1}
                  </span>
                  <h4 className="text-2xl font-serif text-white tracking-tight">
                    {option.style_category}
                  </h4>
                </div>
                <div className="text-right">
                   <span className="text-xs font-mono text-zinc-500 block mb-1">COHESION</span>
                   <span className="text-lg font-mono text-zinc-100 font-bold">{Math.round(option.confidence_score * 100)}%</span>
                </div>
              </div>
              
              <p className="text-zinc-400 text-sm font-sans line-clamp-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 transform translate-y-2 group-hover:translate-y-0">
                {option.metadata?.style_description || "A custom design direction generated by the agent based on your visual prompt."}
              </p>
            </div>

            {/* Interactive Border */}
            <div className="absolute inset-0 border-2 border-amber-500/0 group-hover:border-amber-500/50 transition-colors duration-300 rounded-xl" />
          </motion.div>
        ))}
      </AnimatePresence>

      {/* Loading Overlay */}
      <AnimatePresence>
        {loading && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 z-20 flex items-center justify-center bg-zinc-950/60 backdrop-blur-sm rounded-xl"
          >
            <div className="flex flex-col items-center space-y-4">
              <div className="w-12 h-12 border-2 border-amber-500 border-t-transparent rounded-full animate-spin" />
              <div className="text-amber-500 font-mono text-xs tracking-widest uppercase animate-pulse">
                Analyzing Preference...
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
